### ISSUE TITLE
Dependecies in master brach

### ISSUE THREAD

**Issue by persuader72** [bachp/meta-homeassistant#10]
Hi I pulled last master revision but I have problems with the following recipes in pyro. Can I add the corresponding backports?

requested   python3-jinja2 (>= 2.9.6) \
pyro    python3-jinja2 (>= 2.9.5) \

requested    python3-chardet (= 3.0.4) \
pyro    python3-chardet (= 3.0.2) \

requested   python3-paho-mqtt (= 1.3.0) \
pyro    python3-paho-mqtt (= 1.2) \

requested   python3-sqlalchemy (>= 1.1.13) \
pyro    python3-sqlalchemy (>= 1.1.9) \

**Comment by bachp** [comment]
Master is currently tracking master of poky and meta-oe.

Maybe it is time to add a pyro branch that tracks the current pyro.
Would this help you?

**Comment by persuader72** [comment]
yes thanks because I found a configuration quite stable using pyro on the rpi3, if you want, I can help you to maintain updated the pyro branch with new backports.

**Comment by bachp** [comment]
@persuader72 It would be nice if you could take over maintenance of the pyro branch. If you like to discuss you can join the chat on https://matrix.to/#/#meta-homeassistant:matrix.org or if you prefer I can bridge the channel to IRC.
