### ISSUE TITLE
Rocko

### ISSUE THREAD

**Issue by persuader72** [bachp/meta-homeassistant#28]
Hi,

I created a new branch rocko (on https://github.com/persuader72/meta-homeassistant) and upgraded the ha release to 0.65.3, if you create the branch on your repository I can make a pull request.

Regards
Stefano

**Comment by bachp** [comment]
Well that's bad timing. I just finished the 0.65.5 update on master tonight.

Looks like we did a lot of the same work.
The question now is how can we best synchronize this? It would be best if the rocko and master branch don't diverged too much.

Suggestions?

**Comment by persuader72** [comment]
No problem, If you create the rocko branch, I will fix the missing modules and  I will add it to the backport folder.

**Comment by bachp** [comment]
Thanks. I think I named the folder recipes-bachports with s.

Also please make sure all recipes that also exist in meta-python go to the backports folder.

**Comment by persuader72** [comment]
It's done i started a new rocko branch  from your master and added the missing packages.
The rocko branch is on my fork,

**Comment by bachp** [comment]
Ok thanks. I will have a look at it later and if all is fine I will put is here as rocko branch.

**Comment by bachp** [comment]
I pushed the rocko branch. Thanks for backporting the things.
