### ISSUE TITLE
Problem with RDEPENDS

### ISSUE THREAD

**Issue by persuader72** [bachp/meta-homeassistant#7]
Hi, I'm having a weird problem with dependencies in python3-homeassistant_0.XX.Y.bb. I dont' know if the problem is in the way I configured my yocto build system.

In python3-homeassistant_0.51.2.bb Many packages  declare a specific package version matched with an = operator (ex: python3-aiohttp (= 2.2.5)).

My packaging system (I using opkg) is adding a recipe revision (PR variable) at the end of each built package. In my case python3-aiohttp package is called as python3-aiohttp_2.2.5-r0.
This difference is causing the abort of the task do_rootfs complaining a 'nothing provides ...' error.
Ex. nothing provides python3-requests = 2.14.2 needed by python3-homeassistant-0.51.2 

I temporarily solved the problem creating a parallel copy of the python3-homeassistant_0.51.2.bb  recipe changing all operators from = to >=. Ex python3-aiohttp (= 2.2.5) has been changed in  python3-aiohttp (>=  2.2.5)

Do you now if there is a way to configure the yocto build system in order to ignore the recipe revision field when is checking the package  dependencies?

Regards

**Comment by bachp** [comment]
To be honest I only tried it with rpm so far.

I'm not sure why it should work with >= but not with = when using opkg.

Did you already ask on the Yocto Mailing list or the [#yocto](https://matrix.to/#/#freenode_#yocto:matrix.org) IRC channel?

To give some background, the main reason I have the version there in the RDEPENDS that it helps when upgrading to check what needs to be updated. But if this is causing to much of an issue we might want to remove it.

**Comment by persuader72** [comment]
Ok, I will do some further investigations on yocto community channels, I will keep you informed.
Regards

**Comment by bachp** [comment]
@persuader72 Did you find out something regarding this issue?

**Comment by persuader72** [comment]
Not yet, I asked on the yocto mailing list but replies don't solve the problem. I am inclined to think that is only an opkg related problem.  I think it's more useful leave the recipe as it is.
